const busTimes = [
  { time: '9:30am', route: 'Rohinikannan' },
  { time: '9:35am', route: 'SN Transport' },
  { time: '9:46am', route: 'Souparnika' },
  { time: '10:05am', route: 'Sabeena' },
  { time: '10:30am', route: 'Lakshmi' },
  { time: '10:37am', route: 'KSRTC' },
  { time: '10:37am', route: 'Samarat' },
  { time: '11:08am', route: 'Sree bhadra' },
  { time: '11:40am', route: 'Cheenikkas' },
  { time: '11:53am', route: 'Sabeena' },
  { time: '11:55am', route: 'KSRTC' },
  { time: '12pm', route: 'kalidasan' },
  
  { time: '9:00am',  route: 'St.savio' },
  { time: '9:45am',  route: 'Shankaranarayanan' },
  { time: '9:30am', route: 'Sabeena' },
  { time: '9:36am',  route: 'KSRTC' },
  { time: '10:20am',  route: 'Unnikuttan' },
  { time: '9:54am',  route: 'Infant jesus' },
  
  { time: '10:18am', route: 'Rohini kannan' },
  { time: '12:20pm', route: 'Unnikuttan' },
  { time: '10:31am', route: 'SN Transport' },
  { time: '10:45am', route: 'Sowparnika' },
  { time: '10:50am', route: 'Sreebhadra' },
  { time: '11:20am', route: 'KSRTC' },
  { time: '11:22am', route: 'Sabeena' },
  { time: '12:38pm', route: 'Sree bhadra' },
  { time: '1:05' },
  { time: '1:15pm', route: 'Cheenikkas' },
  { time: '1:51pm', route: 'Sabeena' },
  { time: '3:05pm', route: 'unnikuttan' },
  { time: '3pm', route: 'Lakshmi' },
  { time: '5:15pm', route: 'unnikuttan' },
  { time: '5:50pm', route: 'Shankaranarayanan' },
  { time: '7:02pm', route: 'KSRTC' },
  { time: '12pm', route: 'KSRTC' },
  { time: '12:17pm', route: 'Infant jesus' },
  { time: '12:39pm', route: 'Sree Bhadra' },
  { time: '12:45pm', route: ' SN Transport' },
  { time: '01:03pm', route: 'Lakshmi' },
  { time: '01:05pm', route: 'Rohini kannan' },
  { time: '2:05pm', route: 'KSRTC' },
  { time: '2:34pm', route: 'Sowparnika' },
  { time: '2:46pm', route: 'Sabeena' },
  { time: '3:05pm', to: 'Paravur', route: 'St.savio' },
  { time: '3:19pm', to: 'Paravur', route: 'Samrat' },
  { time: '3:19pm', to: 'Paravur', route: 'Infant jesus' },
  { time: '3:32pm', route: 'KSRTC' },
  { time: '4:18pm', route: 'Cheenikkas' },
  { time: '4:20pm', route: 'kalidasan' },
  { time: '4:56pm', route: ' SN Transport' },
  { time: '5:05pm', route: 'Rohinikannan' },
  { time: '5:25pm', route: 'KSRTC' },
  { time: '5:35pm', route: 'Sabeena' },
  { time: '5:52pm', route: 'KSRTC' },
  { time: '6:25pm', route: 'Infant jesus' },
  { time: '6:30pm', route: 'Lakshmi' },
  { time: '6:33pm', route: 'Sowparnika' },
  { time: '6:39pm', route: 'KSRTC' },
  { time: '6:48pm', route: 'Sree bhadra' },
  { time: '7:02pm', route: 'KSRTC' },
  { time: '7:05pm', route: 'KSRTC' },
  { time: '2:00pm', route: 'Rohinikannan' },
  { time: '2:37pm', route: 'SN Transport' },
  { time: '2:49pm', route: ' KSRTC' },
  { time: '521836' },
  { time: '7.24' },
  { time: '3:58' },
  { time: 'KS2.5-6' },
  { time: '4 pm', route: 'Sowparnika' },
  { time: '4:07 pm', route: 'Infant jesus' },
  { time: '8.10 ·A·m' },
  { time: '4:15 pm', route: 'Sree bhadra' },
  { time: '4:20 pm', route: 'St savio' },
  { time: '8.25' },
  { time: '8.50', k: 'SQ', j: 'J.L' },
  { time: '4:29 pm', route: 'KSRTC' },
  { time: '5 pm', route: 'Sabeena' },
  { time: '5:08 pm', route: 'Cheenikkas' },
  { time: '6 pm', route: 'Rohinikannan' },
  { time: '6:20pm', route: 'SN Transport' },
  { time: '7 pm', route: 'Sabeena' },
  { time: '7:27 pm', route: 'Sowparninka' }
];

const busTimesContainer = document.getElementById('bus-times');

busTimes.forEach(time => {
  const timeElement = document.createElement('div');
  timeElement.classList.add('time');
  if (time.to) {
    timeElement.textContent = `${time.time} - ${time.to} - ${time.route}`;
  } else {
    timeElement.textContent = `${time.time} - ${time.route}`;
  }
  busTimesContainer.appendChild(timeElement);
});